@echo off
echo Checking port 8080...
for /f "tokens=5" %%a in ('netstat -aon ^| findstr ":8080 " ^| findstr "LISTENING"') do (
    echo Killing process %%a on port 8080...
    taskkill /PID %%a /F >nul 2>&1
)
echo Starting Spring Boot...
cd /d "D:\Web-site\Backend-Java"
mvn spring-boot:run
